#pragma once
#include <fea/config.hpp>
#include <fea/audio/efx/reverb.hpp>

namespace fea
{
    enum ReverbPreset {
        GENERIC = 0,
        PADDED_CELL,
        ROOM,
        BATHROOM,
        LIVING_ROOM,
        STONE_ROOM,
        AUDITORIUM,
        CONCERT_HALL,
        CAVE,
        ARENA,
        HANGAR,
        CARPETED_HALLWAY,
        HALLWAY,
        STONE_CORRIDOR,
        ALLEY,
        FOREST,
        CITY,
        MOUNTAINS,
        QUARRY,
        PLAIN,
        PARKING_LOT,
        SEWER_PIPE,
        UNDER_WATER,
        DRUGGED,
        DIZZY,
        PSYCHOTIC,
        CASTLE_SMALL_ROOM,
        CASTLE_SHORT_PASSAGE,
        CASTLE_MEDIUM_ROOM,
        CASTLE_LARGE_ROOM,
        CASTLE_LONG_PASSAGE,
        CASTLE_HALL,
        CASTLE_CUPBOARD,
        CASTLE_COURTYARD,
        CASTLE_ALCOVE,
        FACTORY_SMALL_ROOM,
        FACTORY_SHORT_PASSAGE,
        FACTORY_MEDIUM_ROOM,
        FACTORY_LARGE_ROOM,
        FACTORY_LONG_PASSAGE,
        FACTORY_HALL,
        FACTORY_CUPBOARD,
        FACTORY_COURTYARD,
        FACTORY_ALCOVE,
        ICE_PALACE_SMALL_ROOM,
        ICE_PALACE_SHORT_PASSAGE,
        ICE_PALACE_MEDIUM_ROOM,
        ICE_PALACE_LARGE_ROOM,
        ICE_PALACE_LONG_PASSAGE,
        ICE_PALACE_HALL,
        ICE_PALACE_CUPBOARD,
        ICE_PALACE_COURTYARD,
        ICE_PALACE_ALCOVE,
        SPACE_STATION_SMALL_ROOM,
        SPACE_STATION_SHORT_PASSAGE,
        SPACE_STATION_MEDIUM_ROOM,
        SPACE_STATION_LARGE_ROOM,
        SPACE_STATION_LONG_PASSAGE,
        SPACE_STATION_HALL,
        SPACE_STATION_CUPBOARD,
        SPACE_STATION_ALCOVE,
        WOODEN_SMALL_ROOM,
        WOODEN_SHORT_PASSAGE,
        WOODEN_MEDIUM_ROOM,
        WOODEN_LARGE_ROOM,
        WOODEN_LONG_PASSAGE,
        WOODEN_HALL,
        WOODEN_CUPBOARD,
        WOODEN_COURTYARD,
        WOODEN_ALCOVE,
        SPORT_EMPTY_STADIUM,
        SPORT_SQUASH_COURT,
        SPORT_SMALL_SWIMMING_POOL,
        SPORT_LARGE_SWIMMING_POOL,
        SPORT_GYMNASIUM,
        SPORT_FULL_STADIUM,
        SPORT_STADIUM_TANNOY,
        PREFAB_WORKSHOP,
        PREFAB_SCHOOL_ROOM,
        PREFAB_PRACTISE_ROOM,
        PREFAB_OUTHOUSE,
        PREFAB_CARAVAN,
        DOME_TOMB,
        PIPE_SMALL,
        DOME_SAINTPAULS,
        PIPE_LONG_THIN,
        PIPE_LARGE,
        PIPE_RESONANT,
        OUTDOORS_BACKYARD,
        OUTDOORS_ROLLING_PLAINS,
        OUTDOORS_DEEP_CANYON,
        OUTDOORS_CREEK,
        OUTDOORS_VALLEY,
        MOOD_HEAVEN,
        MOOD_HELL,
        MOOD_MEMORY,
        DRIVING_COMMENTATOR,
        DRIVING_PIT_GARAGE,
        DRIVING_INCAR_RACER,
        DRIVING_INCAR_SPORTS,
        DRIVING_INCAR_LUXURY,
        DRIVING_FULL_GRAND_STAND,
        DRIVING_EMPTY_GRAND_STAND,
        DRIVING_TUNNEL,
        CITY_STREETS,
        CITY_SUBWAY,
        CITY_MUSEUM,
        CITY_LIBRARY,
        CITY_UNDERPASS,
        CITY_ABANDONED,
        DUSTY_ROOM,
        CHAPEL,
        SMALL_WATER_ROOM};

    static void loadReverbPreset(Reverb& reverb, ReverbPreset preset);

    /** @addtogroup Audio
     *@{
     *  @enum ReverbPreset
     *  @fn static void loadReverbPreset(Reverb& reverb, ReverbPreset preset)
     *@}
     ***
     *  @enum ReverbPreset
     *  @brief The reverb presets can be loaded using the loadReverbPreset function.
     ***
     *  @fn static void loadReverbPreset(Reverb& reverb, ReverbPreset preset)
     *  @brief Load reverb presets into a reverb instance.
     ***/
}
