#include <featherkit/audio/audio.hpp>
#include <featherkit/audio/audiosample.hpp>
#include <featherkit/audio/audioplayer.hpp>
#include <featherkit/audio/audiostream.hpp>
#include <featherkit/audio/audiofilestream.hpp>
#include <featherkit/audio/oscillator.hpp>
#include <featherkit/audio/efx/reverb.hpp>
#include <featherkit/audio/efx/chorus.hpp>
#include <featherkit/audio/efx/distortion.hpp>
#include <featherkit/audio/efx/echo.hpp>
#include <featherkit/audio/efx/compressor.hpp>
#include <featherkit/audio/efx/flanger.hpp>
#include <featherkit/audio/efx/ringmodulator.hpp>
#include <featherkit/audio/efx/equalizer.hpp>
