# Find the nasm assembler

SET(ASM_DIALECT "-NASM")

SET(CMAKE_ASM${ASM_DIALECT}_COMPILER_INIT nasm)

IF(NOT CMAKE_ASM${ASM_DIALECT}_COMPILER)
	IF(WIN32)
		SET(CMAKE_ASM${ASM_DIALECT}_COMPILER ${YASM_PATH})
	ELSE(WIN32)
		SET(CMAKE_ASM${ASM_DIALECT}_COMPILER ${YASM_PATH})
	ENDIF(WIN32)
ENDIF(NOT CMAKE_ASM${ASM_DIALECT}_COMPILER)

INCLUDE(CMakeDetermineCompilerId)
INCLUDE(CMakeDetermineASMCompiler)
SET(ASM_DIALECT)