# support for the nasm assembler

SET(ASM_DIALECT "-NASM")

SET(CMAKE_ASM${ASM_DIALECT}_SOURCE_FILE_EXTENSIONS asm)

#detection for bitness. not needed at this time
if(WIN32)
	# if(64_BIT_ASM)
		SET(CMAKE_ASM${ASM_DIALECT}_OBJECT_FORMAT win64)
	# else()
		# SET(CMAKE_ASM${ASM_DIALECT}_OBJECT_FORMAT win32)
	# endif()
endif()

if(UNIX)
	# if(64_BIT_ASM)
		SET(CMAKE_ASM${ASM_DIALECT}_OBJECT_FORMAT elf64)
	# else()
		# SET(CMAKE_ASM${ASM_DIALECT}_OBJECT_FORMAT elf)
	# endif()
endif()

SET(CMAKE_ASM${ASM_DIALECT}_COMPILE_OBJECT "<CMAKE_ASM${ASM_DIALECT}_COMPILER> -f ${CMAKE_ASM${ASM_DIALECT}_OBJECT_FORMAT} -o <OBJECT> <SOURCE> -D ${CMAKE_ASM${ASM_DIALECT}_OBJECT_FORMAT}")

INCLUDE(CMakeASMInformation)
SET(ASM_DIALECT)